apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
#    kubernetes.io/tls-acme: "true"
#    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.org/client-max-body-size: "0"
    nginx.org/proxy-buffer-size: "8k"
  labels:
  name: firefly-iii-importer-ingress
spec:
  rules:
  - host: importer-firefly-iii.your-domain.org
    http:
      paths:
      - backend:
          service:
            name: firefly-iii-importer
            port:
              number: 8080
        path: /
        pathType: Prefix
# tls:
#  - hosts:
#    - importer-firefly-iii.your-domain.org
#    secretName: importer-firefly-iii.your-domain.org-tls

