apiVersion: v2
name: firefly-db
version: 0.2.3
description: Installs a postgres db for Firefly III
type: application
sources:
  - https://github.com/firefly-iii/kubernetes/tree/main/charts/firefly-db
maintainers:
  - name: morremeyer
    email: firefly-iii@mor.re
