apiVersion: v2
name: firefly-iii
description: Installs Firefly III
home: https://www.firefly-iii.org/
icon: https://raw.githubusercontent.com/firefly-iii/firefly-iii/main/.github/assets/img/logo-small.png
type: application
version: 1.9.1
# renovate: image=docker.io/fireflyiii/core
appVersion: 6.2.9
sources:
  - https://github.com/firefly-iii/firefly-iii/
maintainers:
  - name: morremeyer
    email: firefly-iii@mor.re
