apiVersion: v2
name: importer
version: 1.4.0
description: Deploys the importer chart for Firefly III
type: application
home: https://www.firefly-iii.org/
sources:
  - https://github.com/firefly-iii/data-importer
maintainers:
  - name: morremeyer
    email: firefly-iii@mor.re
icon: https://raw.githubusercontent.com/firefly-iii/firefly-iii/main/.github/assets/img/logo-small.png
