{{ if and (.Values.secrets.env) (not .Values.config.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "firefly-iii.fullname" . }}
  labels:
    {{- include "firefly-iii.labels" . | nindent 4 }}
data:
{{- range $key, $value := .Values.secrets.env }}
  {{ $key }}: {{ $value | b64enc | quote }}
{{- end }}
{{- end }}
